___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!

#### 1. Import NumPy Library

In [8]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [9]:
my_list = np.array([5,10,15,20,25])
my_list

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array 5x5 zeros

In [10]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array 4x4 ones assign data type int

In [11]:
np.ones([4,4], dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

> Girintili blok

In [12]:
np.ones([4,4], dtype="int")*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create same array above with full method

In [13]:
np.full([4,4],7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16

In [14]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with values between 0 to 25

*   Liste öğesi
*   Liste öğesi

In [15]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with values between 0 to 25 using linspace

In [16]:
np.linspace(0,24,25, dtype="int").reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create 5 random number with numpy

In [17]:
np.random.rand(5)

array([0.07580718, 0.87335609, 0.19010775, 0.19210863, 0.73014087])

#### 11. Create random normal distributed 5x5 array

In [18]:
np.random.randn(5,5)

array([[-0.66513859, -0.58855552,  0.17509624,  0.49848783,  2.10350067],
       [-0.42043278, -0.82897007, -1.13671855,  1.42209184, -1.37044354],
       [-0.28243803, -0.24992224,  0.3033908 , -1.72953291, -0.97410833],
       [ 0.01968875, -0.12823461,  0.09405772, -0.49846168, -1.13190035],
       [ 1.12780463, -0.53714492,  0.89327302,  0.23579926,  0.36096259]])

#### 12. Create 3x4 shaped array with random int numbers between 20 and 50 with numpy

In [19]:
np.random.randint(20,50,12).reshape(3,4)

array([[25, 40, 38, 28],
       [43, 47, 25, 36],
       [43, 34, 22, 47]])

#### 13. Reshape the array below with shape 6x8

In [20]:
renarr = np.array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])
renarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [22]:
renarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [23]:
renarr.reshape(6,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [24]:
#reshape with -1  #-1 ile otomatik
renarr.reshape(-1,8)

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection

In [25]:
#Create array below
mat= np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Write code that reproduces the output shown below.<br>

In [26]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array.

In [27]:
mat[0:,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [28]:
mat[1,::2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [29]:
mat[:,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [30]:
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1 and last column with step 2.

In [31]:
mat[1::2,::2]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above

In [32]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [33]:
mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [34]:
mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [35]:
mat[mat<10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [36]:
(mat[mat<10]+mat[mat>12]).std()

29.700546274093877

#### 22. Get the sum of second column from array above

In [37]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [38]:
#a =mat[:,1].sum(axis=0)
#a
sum(mat [:,1])

32

#### 23. Get the median,mean and std of 3rd row from array above

In [39]:
mat= np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [40]:
mat[2]

array([ 9, 10, 11, 12])

In [41]:
#median
np.median(mat[2])

10.5

In [42]:
#mean
np.mean(mat[2])

10.5

In [43]:
#std
np.std(mat[2])

1.118033988749895

# Pandas Section

In [44]:
import pandas as pd

**Read Salaries.csv take a look at first 5 rows, df info and df statistical measurements**

In [47]:
salaries=pd.read_csv("Salaries.csv")
salaries

            Id       EmployeeName  ...         Agency  Status
0            1     NATHANIEL FORD  ...  San Francisco     NaN
1            2       GARY JIMENEZ  ...  San Francisco     NaN
2            3     ALBERT PARDINI  ...  San Francisco     NaN
3            4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4            5    PATRICK GARDNER  ...  San Francisco     NaN
...        ...                ...  ...            ...     ...
148649  148650      Roy I Tillery  ...  San Francisco     NaN
148650  148651       Not provided  ...  San Francisco     NaN
148651  148652       Not provided  ...  San Francisco     NaN
148652  148653       Not provided  ...  San Francisco     NaN
148653  148654          Joe Lopez  ...  San Francisco     NaN

[148654 rows x 13 columns]

In [48]:
salaries.head()

   Id       EmployeeName  ...         Agency  Status
0   1     NATHANIEL FORD  ...  San Francisco     NaN
1   2       GARY JIMENEZ  ...  San Francisco     NaN
2   3     ALBERT PARDINI  ...  San Francisco     NaN
3   4  CHRISTOPHER CHONG  ...  San Francisco     NaN
4   5    PATRICK GARDNER  ...  San Francisco     NaN

[5 rows x 13 columns]

In [49]:
salaries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [50]:
salaries.describe()

                  Id        BasePay  ...  Notes  Status
count  148654.000000  148045.000000  ...    0.0     0.0
mean    74327.500000   66325.448841  ...    NaN     NaN
std     42912.857795   42764.635495  ...    NaN     NaN
min         1.000000    -166.010000  ...    NaN     NaN
25%     37164.250000   33588.200000  ...    NaN     NaN
50%     74327.500000   65007.450000  ...    NaN     NaN
75%    111490.750000   94691.050000  ...    NaN     NaN
max    148654.000000  319275.010000  ...    NaN     NaN

[8 rows x 10 columns]

**How many different year value are there**

In [51]:
salaries.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

**Print out max and avg Totalpay**

In [52]:
#max
salaries.TotalPay.max()

567595.43

In [53]:
#avg
salaries.TotalPay.mean()

74768.321971703

**How many records are there which have TotalPay bigger than avg TotalPay**

In [54]:
len(salaries.TotalPay[salaries.TotalPay > salaries.TotalPay.mean()].value_counts())
# df.TotalPay[df.TotalPay>df.TotalPay.mean()].count()

64489

**How much does ALBERT PARDINI make (including benefits)?**

In [55]:
salaries.TotalPayBenefits[salaries["EmployeeName"]=="ALBERT PARDINI"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is lowest paid person**

In [56]:
salaries[salaries.TotalPayBenefits==salaries.TotalPayBenefits.min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [57]:
salaries.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 least common Jobs**

In [58]:
salaries["JobTitle"].value_counts().tail(3)

Public Service Aide-Technical      1
MUNICIPAL STADIUM GROUNDSKEEPER    1
SENIOR PLAN CHECKER                1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012**

In [59]:
salaries[(salaries.TotalPayBenefits>salaries.TotalPayBenefits.mean()) & (salaries.Year==2012)]["EmployeeName"].count()

20366

**How many people have the word Manager in their job title?**

In [60]:
def manager_func(x):
    if 'manager' in x.lower():
        return True
    else:
        return False

In [61]:
len(salaries[salaries.JobTitle.apply(lambda x:manager_func(x))])

4110

**Take Id,EmployeeName,JobTitle,TotalPay and TotalPayBenefits columns with iloc and assign it as sal_new dataframe**

In [62]:
salaries_new=salaries.iloc[:,[0,1,2,7,8]]
salaries_new.head()

   Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0   1     NATHANIEL FORD  ...  567595.43         567595.43
1   2       GARY JIMENEZ  ...  538909.28         538909.28
2   3     ALBERT PARDINI  ...  335279.91         335279.91
3   4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4   5    PATRICK GARDNER  ...  326373.19         326373.19

[5 rows x 5 columns]

In [63]:
salaries_new

            Id       EmployeeName  ...   TotalPay  TotalPayBenefits
0            1     NATHANIEL FORD  ...  567595.43         567595.43
1            2       GARY JIMENEZ  ...  538909.28         538909.28
2            3     ALBERT PARDINI  ...  335279.91         335279.91
3            4  CHRISTOPHER CHONG  ...  332343.61         332343.61
4            5    PATRICK GARDNER  ...  326373.19         326373.19
...        ...                ...  ...        ...               ...
148649  148650      Roy I Tillery  ...       0.00              0.00
148650  148651       Not provided  ...       0.00              0.00
148651  148652       Not provided  ...       0.00              0.00
148652  148653       Not provided  ...       0.00              0.00
148653  148654          Joe Lopez  ...    -618.13           -618.13

[148654 rows x 5 columns]

**Take columns betweeen EmployeeName and TotalPayBenefits with loc and assign it o sal_new df**

In [64]:
salaries_new=salaries_new.loc[:,'EmployeeName':'TotalPayBenefits']
salaries_new

             EmployeeName  ... TotalPayBenefits
0          NATHANIEL FORD  ...        567595.43
1            GARY JIMENEZ  ...        538909.28
2          ALBERT PARDINI  ...        335279.91
3       CHRISTOPHER CHONG  ...        332343.61
4         PATRICK GARDNER  ...        326373.19
...                   ...  ...              ...
148649      Roy I Tillery  ...             0.00
148650       Not provided  ...             0.00
148651       Not provided  ...             0.00
148652       Not provided  ...             0.00
148653          Joe Lopez  ...          -618.13

[148654 rows x 4 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [65]:
salaries[(salaries.TotalPayBenefits>salaries.TotalPayBenefits.min()) & 
       (salaries.TotalPayBenefits<salaries.TotalPayBenefits.mean())]['EmployeeName']

10806            KWE LEE
10807     MIGUEL CARO JR
10808      JOANNE MORRIS
10809      LAYLA WELBORN
10810            LE BANH
               ...
148648       Leon Walker
148649     Roy I Tillery
148650      Not provided
148651      Not provided
148652      Not provided
Name: EmployeeName, Length: 75649, dtype: object